### ISSUE TITLE
Side menu broken styles on larger screens (>540px)

### ISSUE THREAD

**Issue by SvetlinStaev** [FrDH/jQuery.mmenu#845]
Hi,

I have purchased the mmenu and been using it for awhile. It works great! One problem that I keep on getting is when combining the side menu and a fullscreen addon. For some reason the styles of the side menu break on larger screens - over 540px width (including smaller phones when in landscape).

Example: https://www.bezplatno.net/en/1366275
(the full screen addon is the blue message button, the menu is triggered from the top right corner)

The menu pushes the page further than the faded canvas. This happens only on pages having the fullscreen addon, this page doesn't have the addon and it works fine:

https://www.bezplatno.net/

**Comment by FrDH** [comment]
I've seen this issue before but thought is was fixed some time ago.
I found that the CSS causing the issue is somewhere in the HTML of the page (see screenshot). Remove that and you should be OK.

![schermafbeelding 2018-01-24 om 22 57 27](https://user-images.githubusercontent.com/1387163/35359358-1883313e-015a-11e8-8b29-d155f00f0a91.png)

**Comment by SvetlinStaev** [comment]
Yeah, must have been a left over for when it wasn't fixed. Removed it, works great, thanks!
